CORPUS = [
    {"text": "Jon: Have you seen the latest Anthropic release?\nSumit: Yes, it’s impressive.", "label": "news"},    
    {"text": "Jon: Which one is better, Claude or GPT?\nSumit: Depends on the use case.", "label": "comparison"},
    {"text": "Jon: Did you hear about Google’s new AI model?\nSumit: Yes, Gemini is quite powerful.", "label": "news"},
    {"text": "Jon: I prefer smaller models over large ones.\nSumit: True, they’re easier to deploy.", "label": "opinion"},
    {"text": "Jon: Is Meta’s Llama 3 open-source?\nSumit: Yes, it is.", "label": "question"},
    {"text": "Jon: OpenAI’s new API pricing is cheaper.\nSumit: That’s good for startups.", "label": "news"},
    {"text": "Jon: Which framework should we choose for RAG?\nSumit: LangChain or LlamaIndex are solid.", "label": "comparison"},
    {"text": "Jon: I like Anthropic’s focus on safety.\nSumit: Yes, it’s their strong point.", "label": "opinion"},
    {"text": "Jon: Did Hugging Face release a new dataset?\nSumit: Yes, for multilingual tasks.", "label": "news"},
    {"text": "Jon: How does GPT-5 compare to GPT-4?\nSumit: It’s faster and more accurate.", "label": "comparison"},
    {"text": "Jon: Is Gemini better than Claude?\nSumit: Performance-wise, it’s close.", "label": "comparison"},
    {"text": "Jon: I think the AI hype will fade.\nSumit: Possibly, but adoption is growing.", "label": "opinion"},
    {"text": "Jon: Have you tested the new AI translation tool?\nSumit: Yes, works well for Hindi-English.", "label": "news"},
    {"text": "Jon: Which API is cheaper for inference?\nSumit: OpenAI’s new tier beats the rest.", "label": "comparison"},
    {"text": "Jon: Do you think AI will replace coders?\nSumit: It will change the role, not replace.", "label": "opinion"},
    {"text": "Jon: Anthropic added new reasoning features.\nSumit: That’s a big step forward.", "label": "news"},
    {"text": "Jon: Is the fine-tuned model better?\nSumit: Yes, accuracy improved by 10%.", "label": "question"},
    {"text": "Jon: I like how GPT-5 handles context.\nSumit: Yes, long context support is great.", "label": "opinion"},
    {"text": "Jon: Did Microsoft release a Copilot update?\nSumit: Yes, it’s integrated with Teams now.", "label": "news"},
    {"text": "Jon: Is Mistral better for edge devices?\nSumit: Yes, due to its smaller size.", "label": "comparison"},
    {"text": "Jon: I think AI models are becoming too big.\nSumit: True, cost is an issue.", "label": "opinion"},
    {"text": "Jon: Which model has better multilingual support?\nSumit: Gemini beats GPT here.", "label": "comparison"},
    {"text": "Jon: Did Hugging Face host the new model?\nSumit: Yes, it’s available now.", "label": "news"},
    {"text": "Jon: I believe smaller datasets can still be powerful.\nSumit: With good tuning, yes.", "label": "opinion"},
    {"text": "Jon: What’s the latency of GPT-5?\nSumit: Around 800ms for short prompts.", "label": "question"},
    {"text": "Jon: I feel Claude is more polite in answers.\nSumit: Yes, its tone is softer.", "label": "opinion"},
    {"text": "Jon: OpenAI is adding speech-to-text.\nSumit: That’s going to help accessibility.", "label": "news"},
    {"text": "Jon: Which fine-tuning method do you like?\nSumit: LoRA for cost and efficiency.", "label": "opinion"},
    {"text": "Jon: Is OpenAI’s GPT-5 faster than Claude?\nSumit: Yes, by about 30%.", "label": "comparison"},
    {"text": "Jon: Google added code generation to Gemini.\nSumit: That’s great for devs.", "label": "news"},
    {"text": "Jon: I think RAG is overrated.\nSumit: It depends on the use case.", "label": "opinion"},
    {"text": "Jon: Which one is better for summarization?\nSumit: Claude handles longer texts better.", "label": "comparison"},
    {"text": "Jon: Did you try the new Hugging Face Spaces?\nSumit: Yes, the UI is much faster.", "label": "news"},
    {"text": "Jon: I feel fine-tuning is better than prompt engineering.\nSumit: Agreed, more control.", "label": "opinion"},
    {"text": "Jon: Which platform is better for hosting models?\nSumit: AWS Bedrock or Hugging Face.", "label": "comparison"},
    {"text": "Jon: Anthropic just improved their API rate limits.\nSumit: That’s a relief.", "label": "news"},
    {"text": "Jon: I prefer serverless AI hosting.\nSumit: Easier scaling, yes.", "label": "opinion"},
    {"text": "Jon: Which model has better coding skills?\nSumit: GPT-5, from my tests.", "label": "comparison"},
    {"text": "Jon: Did Microsoft release their new vision model?\nSumit: Yes, yesterday.", "label": "news"},
    {"text": "Jon: I think large models should be open-sourced.\nSumit: That’s a bold move.", "label": "opinion"},
    {"text": "Jon: Which AI is better for low-resource languages?\nSumit: Llama 3 does well.", "label": "comparison"},
    {"text": "Jon: Google added live translation to Gemini.\nSumit: That’s game-changing.", "label": "news"},
    {"text": "Jon: I think Claude feels more human in tone.\nSumit: True, especially in casual chats.", "label": "opinion"},
    {"text": "Jon: Which one responds faster to short queries?\nSumit: GPT-5.", "label": "comparison"},
    {"text": "Jon: Did Hugging Face integrate with VS Code?\nSumit: Yes, as a plugin.", "label": "news"},
    {"text": "Jon: AI is getting too commercial.\nSumit: That’s inevitable.", "label": "opinion"},
    {"text": "Jon: Which is better for document QA?\nSumit: RAG-based GPT models.", "label": "comparison"},
    {"text": "Jon: OpenAI added multi-modal features.\nSumit: That’s impressive.", "label": "news"},
    {"text": "Jon: I like Anthropic’s customer support.\nSumit: Very responsive.", "label": "opinion"},
    {"text": "Jon: Which model works best offline?\nSumit: Smaller Mistral variants.", "label": "comparison"},
    {"text": "Jon: Microsoft’s Copilot can now summarize calls.\nSumit: That’s super handy.", "label": "news"},
    {"text": "Jon: I feel Gemini is too slow.\nSumit: That’s true under load.", "label": "opinion"},
    {"text": "Jon: Which model is cheapest for bulk inference?\nSumit: Llama 3.", "label": "comparison"},
    {"text": "Jon: Did OpenAI announce GPT Store?\nSumit: Yes, with custom GPTs.", "label": "news"},
    {"text": "Jon: I prefer smaller prompts.\nSumit: Easier to control output.", "label": "opinion"},
    {"text": "Jon: Which AI handles jokes better?\nSumit: Claude.", "label": "comparison"},
    {"text": "Jon: Hugging Face just added model monitoring.\nSumit: That’s useful for tracking drift.", "label": "news"},
    {"text": "Jon: I think fine-tuning is expensive.\nSumit: True, but it pays off.", "label": "opinion"},
    {"text": "Jon: Which AI is better for summarizing PDFs?\nSumit: GPT-5 handles them well.", "label": "comparison"},
    {"text": "Jon: OpenAI launched new embeddings.\nSumit: That’ll help semantic search.", "label": "news"},
    {"text": "Jon: I believe AI should be regulated.\nSumit: Agreed.", "label": "opinion"},
    {"text": "Jon: Which one has better API docs?\nSumit: Anthropic’s are cleaner.", "label": "comparison"},
    {"text": "Jon: Google released Gemini 1.5.\nSumit: Big improvement over 1.0.", "label": "news"},
    {"text": "Jon: I like fine-tuning smaller models.\nSumit: Cost-effective.", "label": "opinion"},
    {"text": "Jon: Which AI is better at coding contests?\nSumit: GPT-5.", "label": "comparison"},
    {"text": "Jon: Microsoft added multi-agent support.\nSumit: That’s powerful.", "label": "news"},
    {"text": "Jon: I think multi-modal is the future.\nSumit: Definitely.", "label": "opinion"},
    {"text": "Jon: Which model handles images better?\nSumit: Gemini.", "label": "comparison"},
    {"text": "Jon: Hugging Face supports LoRA training now.\nSumit: That’s helpful.", "label": "news"},
    {"text": "Jon: AI assistants should have personality.\nSumit: Yes, makes them engaging.", "label": "opinion"},
    {"text": "Jon: Which platform is better for prototypes?\nSumit: Hugging Face Spaces.", "label": "comparison"},
    {"text": "Jon: OpenAI reduced token prices.\nSumit: That’s great for devs.", "label": "news"},
    {"text": "Jon: I like conversational AI more than search.\nSumit: It’s more natural.", "label": "opinion"},
    {"text": "Jon: Which AI is best for creative writing?\nSumit: Claude.", "label": "comparison"},
    {"text": "Jon: Anthropic is adding more languages.\nSumit: That’s good for global users.", "label": "news"},
    {"text": "Jon: I think smaller models are underrated.\nSumit: Absolutely.", "label": "opinion"},
    {"text": "Jon: Which one is better at debugging code?\nSumit: GPT-5.", "label": "comparison"},
    {"text": "Jon: Hugging Face launched a model leaderboard.\nSumit: Great for tracking benchmarks.", "label": "news"},
    {"text": "Jon: I feel AI-generated images lack depth.\nSumit: Sometimes, yes.", "label": "opinion"},
    {"text": "Jon: Which model is better for speech synthesis?\nSumit: ElevenLabs’ API.", "label": "comparison"},
    {"text": "Jon: Microsoft integrated Copilot in Word.\nSumit: That’ll help writers.", "label": "news"},
    {"text": "Jon: I think AI will change education.\nSumit: No doubt.", "label": "opinion"},
    {"text": "Jon: Which AI is better for chatbots?\nSumit: GPT-5.", "label": "comparison"},
    {"text": "Jon: Google added video understanding to Gemini.\nSumit: That’s next level.", "label": "news"},
    {"text": "Jon: I prefer lightweight models.\nSumit: Easier to deploy.", "label": "opinion"},
    {"text": "Jon: Which AI handles sarcasm better?\nSumit: Claude.", "label": "comparison"},
    {"text": "Jon: OpenAI improved tool use in GPT.\nSumit: That’s more flexible.", "label": "news"},
    {"text": "Jon: I think AI models should be explainable.\nSumit: Transparency matters.", "label": "opinion"},
    {"text": "Jon: Which one is better for translation?\nSumit: Gemini.", "label": "comparison"},
    {"text": "Jon: Hugging Face added dataset versioning.\nSumit: That’s great for research.", "label": "news"},
    {"text": "Jon: I feel RAG works best with domain data.\nSumit: Agreed.", "label": "opinion"},
    {"text": "Jon: Which platform is better for enterprise AI?\nSumit: AWS Bedrock.", "label": "comparison"},
    {"text": "Jon: Anthropic added API key rotation.\nSumit: That’s safer.", "label": "news"},
    {"text": "Jon: I think chat memory is essential.\nSumit: Makes it more human.", "label": "opinion"},
    {"text": "Jon: Which AI responds better to long queries?\nSumit: GPT-5.", "label": "comparison"},
    {"text": "Jon: OpenAI’s GPT-5 has better fact-checking.\nSumit: That’s useful.", "label": "news"},
    {"text": "Jon: I prefer structured prompts.\nSumit: Keeps it predictable.", "label": "opinion"},
    {"text": "Jon: Which AI works best for math problems?\nSumit: GPT-5.", "label": "comparison"},
    {"text": "Jon: Google released Gemini API SDK.\nSumit: That’ll help devs.", "label": "news"}
]
